import {
  Album,
  AlignHorizontalJustifyCenter,
  Aperture,
  ArrowLeft,
  ArrowDown,
  ArrowUp,
  BringToFront,
  Camera,
  Check,
  Crop,
  ChevronLeft,
  CircleCheck,
  CircleHelp,
  ChevronRight,
  ChevronsUpDown,
  ChevronsDown,
  ChevronsUp,
  Cloud,
  CloudAlert,
  CloudCheck,
  CloudDownload,
  CloudOff,
  CloudUpload,
  Database,
  Download,
  Eye,
  EyeOff,
  FileKey,
  Fingerprint,
  FlipHorizontal2,
  Folder,
  Funnel,
  FolderOpen,
  Grid2x2,
  Grid3x3,
  GripVertical,
  Group,
  HardDrive,
  Image,
  ImageDown,
  ImageOff,
  Images,
  Info,
  KeyRound,
  Keyboard,
  Layers,
  Plus,
  LayoutDashboard,
  LayoutGrid,
  List,
  Lock,
  MapPin,
  Maximize2,
  Minus,
  PanelLeftClose,
  PanelLeftOpen,
  Pause,
  Play,
  RefreshCw,
  RotateCcw,
  RotateCw,
  Search,
  SendToBack,
  Settings2,
  Share,
  ShieldCheck,
  SlidersHorizontal,
  Square,
  Star,
  Trash2,
  TriangleAlert,
  Upload,
  X,
  ZoomIn,
  ZoomOut,
  Captions,
  Film,
  Loader,
  Maximize,
  Music,
  Volume2,
  VolumeX,
} from 'lucide-react';
import type { ReactElement } from 'react';

import './icon.css';

// The design system's fixed icon vocabulary (DS readme §ICONOGRAPHY) — using
// any other glyph is a type error, not a review comment. No emoji, no icon
// fonts, no ad-hoc SVGs, no CDN: lucide-react is bundled and tree-shaken.
export const ICON_NAMES = [
  'album',
  'align-horizontal-justify-center',
  'aperture',
  'arrow-left',
  'arrow-down',
  'arrow-up',
  'bring-to-front',
  'camera',
  'check',
  'crop',
  'chevron-left',
  'chevron-right',
  'chevrons-up-down',
  'chevrons-down',
  'chevrons-up',
  'circle-check',
  'circle-help',
  'folder',
  'cloud',
  'cloud-alert',
  'cloud-check',
  'cloud-download',
  'cloud-off',
  'cloud-upload',
  'database',
  'download',
  'eye',
  'eye-off',
  'file-key',
  'fingerprint',
  'flip-horizontal-2',
  'folder-open',
  'funnel',
  'grid-2x2',
  'grid-3x3',
  'grip-vertical',
  'group',
  'hard-drive',
  'image',
  'image-down',
  'image-off',
  'images',
  'info',
  'key-round',
  'keyboard',
  'layers',
  'layout-dashboard',
  'layout-grid',
  'list',
  'lock',
  'map-pin',
  'maximize-2',
  'minus',
  'panel-left-close',
  'panel-left-open',
  'pause',
  'play',
  'plus',
  'refresh-cw',
  'rotate-ccw',
  'rotate-cw',
  'search',
  'send-to-back',
  'settings-2',
  'share',
  'shield-check',
  'sliders-horizontal',
  'square',
  'star',
  'trash-2',
  'triangle-alert',
  'upload',
  'x',
  'zoom-in',
  'zoom-out',
  // Video transport + kind iconography (#548, ADR-0026 §5/§6/§7).
  'captions',
  'film',
  'loader',
  'maximize',
  'music',
  'volume-2',
  'volume-x',
] as const;

export type IconName = (typeof ICON_NAMES)[number];

/** Directional navigation glyphs mirror in RTL. Physical operations such as
 * rotate and flip are deliberately excluded (ADR-0020 §5). */
export const RTL_MIRRORED_ICON_NAMES = [
  'arrow-left',
  'chevron-left',
  'chevron-right',
  'panel-left-close',
  'panel-left-open',
] as const satisfies readonly IconName[];
const RTL_MIRRORED_ICONS = new Set<IconName>(RTL_MIRRORED_ICON_NAMES);

// `satisfies` proves every vocabulary name has a glyph and no extras exist.
const ICONS = {
  album: Album,
  'align-horizontal-justify-center': AlignHorizontalJustifyCenter,
  aperture: Aperture,
  'arrow-left': ArrowLeft,
  'arrow-down': ArrowDown,
  'arrow-up': ArrowUp,
  'bring-to-front': BringToFront,
  camera: Camera,
  check: Check,
  crop: Crop,
  'chevron-left': ChevronLeft,
  'circle-check': CircleCheck,
  'circle-help': CircleHelp,
  'chevron-right': ChevronRight,
  'chevrons-up-down': ChevronsUpDown,
  'chevrons-down': ChevronsDown,
  'chevrons-up': ChevronsUp,
  cloud: Cloud,
  'cloud-alert': CloudAlert,
  'cloud-check': CloudCheck,
  'cloud-download': CloudDownload,
  'cloud-off': CloudOff,
  'cloud-upload': CloudUpload,
  database: Database,
  download: Download,
  eye: Eye,
  'eye-off': EyeOff,
  'file-key': FileKey,
  fingerprint: Fingerprint,
  'flip-horizontal-2': FlipHorizontal2,
  folder: Folder,
  'folder-open': FolderOpen,
  funnel: Funnel,
  'grid-2x2': Grid2x2,
  'grid-3x3': Grid3x3,
  'grip-vertical': GripVertical,
  group: Group,
  'hard-drive': HardDrive,
  image: Image,
  'image-down': ImageDown,
  'image-off': ImageOff,
  images: Images,
  info: Info,
  'key-round': KeyRound,
  keyboard: Keyboard,
  layers: Layers,
  'layout-dashboard': LayoutDashboard,
  'layout-grid': LayoutGrid,
  list: List,
  lock: Lock,
  'map-pin': MapPin,
  'maximize-2': Maximize2,
  minus: Minus,
  'panel-left-close': PanelLeftClose,
  'panel-left-open': PanelLeftOpen,
  pause: Pause,
  play: Play,
  plus: Plus,
  'refresh-cw': RefreshCw,
  'rotate-ccw': RotateCcw,
  'rotate-cw': RotateCw,
  search: Search,
  'send-to-back': SendToBack,
  'settings-2': Settings2,
  share: Share,
  'shield-check': ShieldCheck,
  'sliders-horizontal': SlidersHorizontal,
  square: Square,
  star: Star,
  'trash-2': Trash2,
  'triangle-alert': TriangleAlert,
  upload: Upload,
  x: X,
  'zoom-in': ZoomIn,
  'zoom-out': ZoomOut,
  captions: Captions,
  film: Film,
  loader: Loader,
  maximize: Maximize,
  music: Music,
  'volume-2': Volume2,
  'volume-x': VolumeX,
} satisfies Record<IconName, typeof Album>;

// 14/16/20 are the DS's stated sizes; 11 (Badge glyphs), 12 (Chip remove),
// 13 (TitleBar controls, Chip glyphs), and 18 (lg Button) are the design
// mock's own additional usages, adopted as-is — as are the minus/square/x
// window-control glyphs above.
// 15 and 28 come from the design's own Toolbar.jsx / LibraryGrid.jsx usage.
// 40 is the drop overlay's hero glyph (#237, index.html).
// 9 is the grid duration/kind-pill glyph (#548, design PhotoTile.jsx).
export type IconSize = 9 | 11 | 12 | 13 | 14 | 15 | 16 | 18 | 20 | 28 | 40;

export interface IconProps {
  readonly name: IconName;
  readonly size?: IconSize;
  /** Defaults to currentColor so icons inherit text color/tokens. */
  readonly color?: string;
  /** 1.75 everywhere except Badge glyphs (2 at 11px) and Checkbox marks (3
   * at 11px) per the mock. */
  readonly strokeWidth?: 1.75 | 2 | 3;
}

export function Icon({ name, size = 16, color = 'currentColor', strokeWidth = 1.75 }: IconProps): ReactElement {
  const Glyph = ICONS[name];
  return (
    <Glyph
      className={RTL_MIRRORED_ICONS.has(name) ? 'ovl-icon--mirror-rtl' : undefined}
      data-icon-name={name}
      size={size}
      strokeWidth={strokeWidth}
      color={color}
      aria-hidden
      style={{ flex: 'none' }}
    />
  );
}
