#!/usr/bin/env node

// Extract the message catalog from the renderer and compile it for the runtime
// (#403, ADR-0020 §1/§6). `src/shared/i18n/messages/en.json` is the committed
// source catalog (extracted format, the ratchet mirror); the renderer imports
// the compiled string map at `src/renderer/src/i18n/generated/en.ts`. CI's
// extraction gate fails if either drifts from the code — the catalog can never
// silently diverge from the components.
//
//   npm run i18n:extract          # regenerate both committed files
//   npm run i18n:extract -- --check   # exit non-zero if either is stale

import { execFileSync } from 'node:child_process';
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import process from 'node:process';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const FORMATJS = path.join(ROOT, 'node_modules', '.bin', 'formatjs');
const EN_JSON = path.join(ROOT, 'src', 'shared', 'i18n', 'messages', 'en.json');
const GENERATED_EN = path.join(ROOT, 'src', 'renderer', 'src', 'i18n', 'generated', 'en.ts');

// Extract from renderer + shared source (where user-facing copy lives). Stories,
// tests, and type decls are fixtures and never carry shippable strings — kept
// out so the catalog stays the real inventory (consistent with the ratchet's
// story exclusion, ADR §6).
const SOURCE_GLOBS = ['src/**/*.ts', 'src/**/*.tsx'];
const IGNORE_GLOBS = ['**/*.test.ts', '**/*.test.tsx', '**/*.stories.tsx', '**/*.d.ts'];

const GENERATED_HEADER = `// GENERATED by scripts/i18n-catalog.mjs from src/shared/i18n/messages/en.json.
// Do not edit by hand — run \`npm run i18n:extract\`. The extraction gate
// (\`npm run i18n:check\`) fails CI if this file drifts from the source catalog.
// Compiled id → message string; the renderer's IntlProvider messages for \`en\`,
// and the base every pseudo-locale is derived from.`;

/** Stable stringify with sorted keys so the committed files diff cleanly. */
function stableJson(record) {
  const sorted = Object.fromEntries(
    Object.keys(record)
      .sort()
      .map((key) => [key, record[key]]),
  );
  return `${JSON.stringify(sorted, null, 2)}\n`;
}

function renderGeneratedEn(compiled) {
  const sorted = Object.keys(compiled).sort();
  const entries = sorted.map((id) => `  ${JSON.stringify(id)}: ${JSON.stringify(compiled[id])},`);
  const body = entries.length === 0 ? '{}' : `{\n${entries.join('\n')}\n}`;
  return `${GENERATED_HEADER}\n\nexport const en: Readonly<Record<string, string>> = ${body};\n`;
}

function withTempDir(run) {
  const dir = mkdtempSync(path.join(tmpdir(), 'overlook-i18n-'));
  try {
    return run(dir);
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
}

/** Extracted catalog (id → { defaultMessage, description }) straight from code. */
function extractCatalog(tempDir) {
  const outFile = path.join(tempDir, 'extracted.json');
  const ignores = IGNORE_GLOBS.flatMap((glob) => ['--ignore', glob]);
  execFileSync(FORMATJS, ['extract', ...SOURCE_GLOBS, '--out-file', outFile, ...ignores], {
    cwd: ROOT,
    stdio: ['ignore', 'ignore', 'inherit'],
  });
  return JSON.parse(readFileSync(outFile, 'utf8'));
}

/** Compile an extracted catalog to the runtime string map (id → message). */
function compileCatalog(extracted, tempDir) {
  const inFile = path.join(tempDir, 'source.json');
  const outFile = path.join(tempDir, 'compiled.json');
  writeFileSync(inFile, stableJson(extracted));
  execFileSync(FORMATJS, ['compile', inFile, '--out-file', outFile], {
    cwd: ROOT,
    stdio: ['ignore', 'ignore', 'inherit'],
  });
  return JSON.parse(readFileSync(outFile, 'utf8'));
}

function readIfPresent(file) {
  try {
    return readFileSync(file, 'utf8');
  } catch {
    return null;
  }
}

function main() {
  const check = process.argv.includes('--check');

  const { enJson, generatedEn } = withTempDir((tempDir) => {
    const extracted = extractCatalog(tempDir);
    const compiled = compileCatalog(extracted, tempDir);
    return { enJson: stableJson(extracted), generatedEn: renderGeneratedEn(compiled) };
  });

  if (check) {
    const stale = [];
    if (readIfPresent(EN_JSON) !== enJson) stale.push(path.relative(ROOT, EN_JSON));
    if (readIfPresent(GENERATED_EN) !== generatedEn) stale.push(path.relative(ROOT, GENERATED_EN));
    if (stale.length > 0) {
      console.error('i18n catalog is stale — run `npm run i18n:extract` and commit:');
      for (const file of stale) console.error(`  - ${file}`);
      process.exit(1);
    }
    console.log('i18n catalog is in sync with the code.');
    return;
  }

  writeFileSync(EN_JSON, enJson);
  writeFileSync(GENERATED_EN, generatedEn);
  console.log('i18n catalog regenerated.');
}

main();
