#!/usr/bin/env node

// Extract the message catalog from the renderer and compile it for the runtime
// (#403, ADR-0020 §1/§6). `src/shared/i18n/messages/en.json` is the committed
// source catalog (extracted format, the ratchet mirror); every
// `messages/<locale>.json` alongside it (hand-authored translations in the same
// format) compiles to `src/renderer/src/i18n/generated/<locale>.ts`, and
// `generated/index.ts` maps locale → catalog so adding a language stays a data
// change: drop in the JSON, run `npm run i18n:extract`, list it in
// SHIPPED_LOCALES. CI's extraction gate fails if any generated file drifts from
// its source — the catalog can never silently diverge from the components.
//
//   npm run i18n:extract          # regenerate the committed files
//   npm run i18n:extract -- --check   # exit non-zero if any is stale

import { execFileSync } from 'node:child_process';
import { mkdtempSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import process from 'node:process';
import { fileURLToPath } from 'node:url';
import { createRequire } from 'node:module';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
// Resolve the CLI's JS entry and run it with the current node binary rather
// than the .bin shim: on Windows the shim is a .cmd that execFileSync cannot
// spawn without a shell, so the shim path is platform-dependent (PR #473
// review). The bin file itself is plain ESM.
const require = createRequire(import.meta.url);
const FORMATJS_PKG = path.dirname(require.resolve('@formatjs/cli/package.json'));
const FORMATJS_BIN = path.join(FORMATJS_PKG, require('@formatjs/cli/package.json').bin.formatjs);
const MESSAGES_DIR = path.join(ROOT, 'src', 'shared', 'i18n', 'messages');
const EN_JSON = path.join(MESSAGES_DIR, 'en.json');
const GENERATED_DIR = path.join(ROOT, 'src', 'renderer', 'src', 'i18n', 'generated');

// Extract from renderer + shared source (where user-facing copy lives). Stories,
// tests, and type decls are fixtures and never carry shippable strings — kept
// out so the catalog stays the real inventory (consistent with the ratchet's
// story exclusion, ADR §6).
const SOURCE_GLOBS = ['src/**/*.ts', 'src/**/*.tsx'];
const IGNORE_GLOBS = ['**/*.test.ts', '**/*.test.tsx', '**/*.stories.tsx', '**/*.d.ts'];

const generatedHeader = (locale) => `// GENERATED by scripts/i18n-catalog.mjs from src/shared/i18n/messages/${locale}.json.
// Do not edit by hand — run \`npm run i18n:extract\`. The extraction gate
// (\`npm run i18n:check\`) fails CI if this file drifts from the source catalog.
// Compiled id → message string for the renderer's IntlProvider.`;

const INDEX_HEADER = `// GENERATED by scripts/i18n-catalog.mjs — the locale → compiled-catalog map.
// Do not edit by hand — run \`npm run i18n:extract\`. One entry per
// src/shared/i18n/messages/<locale>.json; the loader walks the BCP-47 fallback
// chain against these keys, so adding a language is a data change only.`;

/** Stable stringify with sorted keys so the committed files diff cleanly. */
function stableJson(record) {
  const sorted = Object.fromEntries(
    Object.keys(record)
      .sort()
      .map((key) => [key, record[key]]),
  );
  return `${JSON.stringify(sorted, null, 2)}\n`;
}

/** A locale tag as a TS identifier for the generated modules: pt-BR → pt_BR. */
const identifierFor = (locale) => locale.replace(/-/gu, '_');

function renderGeneratedCatalog(locale, compiled) {
  const sorted = Object.keys(compiled).sort();
  const entries = sorted.map((id) => `  ${JSON.stringify(id)}: ${JSON.stringify(compiled[id])},`);
  const body = entries.length === 0 ? '{}' : `{\n${entries.join('\n')}\n}`;
  return `${generatedHeader(locale)}\n\nexport const ${identifierFor(locale)}: Readonly<Record<string, string>> = ${body};\n`;
}

function renderIndex(locales) {
  const sorted = [...locales].sort();
  const imports = sorted.map((locale) => `import { ${identifierFor(locale)} } from './${locale}.js';`).join('\n');
  const entries = sorted.map((locale) => `  ${JSON.stringify(locale)}: ${identifierFor(locale)},`).join('\n');
  return `${INDEX_HEADER}\n\n${imports}\n\nexport const catalogs: Readonly<Record<string, Readonly<Record<string, string>>>> = {\n${entries}\n};\n`;
}

function withTempDir(run) {
  const dir = mkdtempSync(path.join(tmpdir(), 'overlook-i18n-'));
  try {
    return run(dir);
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
}

function runFormatjs(args) {
  execFileSync(process.execPath, [FORMATJS_BIN, ...args], {
    cwd: ROOT,
    stdio: ['ignore', 'ignore', 'inherit'],
  });
}

/** Extracted catalog (id → { defaultMessage, description }) straight from code. */
function extractCatalog(tempDir) {
  const outFile = path.join(tempDir, 'extracted.json');
  const ignores = IGNORE_GLOBS.flatMap((glob) => ['--ignore', glob]);
  runFormatjs(['extract', ...SOURCE_GLOBS, '--out-file', outFile, ...ignores]);
  return JSON.parse(readFileSync(outFile, 'utf8'));
}

/** Compile an extracted-format catalog to the runtime string map (id → message). */
function compileCatalog(extracted, tempDir, label) {
  const inFile = path.join(tempDir, `${label}.source.json`);
  const outFile = path.join(tempDir, `${label}.compiled.json`);
  writeFileSync(inFile, stableJson(extracted));
  runFormatjs(['compile', inFile, '--out-file', outFile]);
  return JSON.parse(readFileSync(outFile, 'utf8'));
}

/** Locale tags of every committed translation file, en excluded. */
function translationLocales() {
  return readdirSync(MESSAGES_DIR)
    .filter((name) => name.endsWith('.json') && name !== 'en.json')
    .map((name) => name.slice(0, -'.json'.length));
}

function readIfPresent(file) {
  try {
    return readFileSync(file, 'utf8');
  } catch {
    return null;
  }
}

function main() {
  const check = process.argv.includes('--check');

  const files = withTempDir((tempDir) => {
    const extracted = extractCatalog(tempDir);
    const locales = ['en', ...translationLocales()];
    const out = new Map([[EN_JSON, stableJson(extracted)]]);
    for (const locale of locales) {
      const source = locale === 'en' ? extracted : JSON.parse(readFileSync(path.join(MESSAGES_DIR, `${locale}.json`), 'utf8'));
      const compiled = compileCatalog(source, tempDir, locale);
      out.set(path.join(GENERATED_DIR, `${locale}.ts`), renderGeneratedCatalog(locale, compiled));
    }
    out.set(path.join(GENERATED_DIR, 'index.ts'), renderIndex(locales));
    return out;
  });

  if (check) {
    const stale = [...files].filter(([file, content]) => readIfPresent(file) !== content).map(([file]) => path.relative(ROOT, file));
    if (stale.length > 0) {
      console.error('i18n catalog is stale — run `npm run i18n:extract` and commit:');
      for (const file of stale) console.error(`  - ${file}`);
      process.exit(1);
    }
    console.log('i18n catalog is in sync with the code.');
    return;
  }

  for (const [file, content] of files) writeFileSync(file, content);
  console.log(`i18n catalog regenerated (${files.size} files).`);
}

main();
